nowsprinting/test-helper.ui

README.md
Runtime/InteractiveComponent.cs
Runtime/Operators/ClickOperator.cs
Runtime/Operators/LongTapOperator.cs
Runtime/Random/IRandom.cs
Tests/Runtime/MonkeyTest.cs
package.json

- Unuse C#8.0 syntax sugar
- Remove test-framework v1.3 from dependencies
- Mod README.md

Unuse C#8.0 syntax sugar

---

.github/workflows/test.yml

- Remove pin install packages version in test workflow
- Upgrade Unity to 2022.2.19f1 for test run on CI

Remove pin install packages version in test workflow

---

Runtime/Monkey.cs
Tests/Runtime/MonkeyTest.cs

Hi, I want only a part of `Run` to branch by a condition in `Run()` as following:
```csharp
public static async UniTask Run(MonkeyConfig config, CancellationToken cancellationToken = default)
{
var endTime = config.Lifetime == TimeSpan.MaxValue
? TimeSpan.MaxValue.TotalSeconds
: config.Lifetime.Add(TimeSpan.FromSeconds(Time.time)).TotalSeconds;
config.Logger.Log($"Using {config.Random}");
var lastOperationTime = Time.time;
while (Time.time < endTime)
{
if (SomeConditionSatisifed) // added
{                           // added
DoSomething();          // added
}                           // added
else                        // added
{                           // added
var didAct = await RunStep(config, cancellationToken);
if (didAct)
{
lastOperationTime = Time.time;
}
else if …
```

Cut out RunStep from Run

---

Runtime/Operators/TouchAndHoldOperator.cs
Tests/Runtime/Operators/TouchAndHoldOperatorTest.cs
Tests/Runtime/TestDoubles/StubDestroyingItselfWhenPointerDown.cs
Tests/Runtime/TestDoubles/StubDestroyingItselfWhenPointerDown.cs.meta
Tests/Scenes/Operators.unity

An interactive component that held by TouchAndHold can get destroyed ~after delayMilis elappsed~ **during delayMilis**. Then TouchAndHold throw the following error:
> MissingReferenceException: The object of type 'Button' has been
> destroyed but you are still trying to access it. Your script should
> either check if it is null or you should not destroy the object.
This patch introduce null-check after delayMilis elappsed.

Fix MissingReferenceException

---

Runtime/InteractiveComponent.cs
Runtime/Operators/TouchAndHoldOperator.cs

There were two places where `Task` was used.
All async methods using `UniTask`.

Replace Task to UniTask

---

Tests/Runtime/AssemblyInfo.cs
Tests/Runtime/AssemblyInfo.cs.meta
Tests/Runtime/InteractiveComponentCollectorTest.cs
Tests/Runtime/InteractiveComponentTest.cs
Tests/Runtime/MonkeyTest.cs
Tests/Runtime/Operators/ClickOperatorTest.cs
Tests/Runtime/Operators/TouchAndHoldOperatorTest.cs

In the future, I would like to standardize the screen resolution to VGA.
Currently, some scenes and tests need to be modified, so we will specify the screen resolution for each class so that only the necessary ones run in Full HD and the rest run in VGA.

Mod screen resolution specify for each class in tests

---

Editor/ContextMenu.meta
Editor/ContextMenu/HintComponentMenu.cs
Editor/ContextMenu/HintComponentMenu.cs.meta
Editor/Localization/ja.po
Editor/TestHelper.Monkey.Editor.asmdef
Editor/UI/Hints.meta
Editor/UI/Hints/InteractiveComponentHintEditor.cs
Editor/UI/Hints/InteractiveComponentHintEditor.cs.meta
Editor/UI/Hints/InteractiveComponentHintGizmoDrawer.cs
Editor/UI/Hints/InteractiveComponentHintGizmoDrawer.cs.meta
Runtime/CameraSelector.cs
Runtime/CameraSelector.cs.meta
Runtime/Hints.meta
Runtime/Hints/InteractiveComponentHint.cs
Runtime/Hints/InteractiveComponentHint.cs.meta
Runtime/Hints/InteractiveComponentHintPosition.cs
Runtime/Hints/InteractiveComponentHintPosition.cs.meta
Runtime/InteractiveComponent.cs
Runtime/ScreenPointStrategies/GameObjectPosition.cs
Tests/Runtime/Hints.meta
Tests/Runtime/Hints/InteractiveComponentHintPositionTest.cs
Tests/Runtime/Hints/InteractiveComponentHintPositionTest.cs.meta
Tests/Runtime/TestDoubles/SpyOnPointerDownUpHandler.cs
Tests/Scenes/Annotations.unity
Tests/Scenes/Hints.unity
Tests/Scenes/Hints.unity.meta
Tests/Scenes/HintsSettings.lighting
Tests/Scenes/HintsSettings.lighting.meta

I implemented hints for interactive components on SceneView and GameView. Related #45.
Hints for components on canvas that has screen space overlay as the render mode are not rendered on GameView. There are on only SceneView.

Show hints for interactive components on SceneView and GameView (only if Gizmoz enabled)

---

package.json

In my project, the Editor directory got missing when I installed test-helper.monkey via Git URL.
I suspect this cause is "files" in package.json.

Add "Editor" to package.json

---

.github/workflows/test.yml

Because of Unity authentication error.

Make Do not run tests on public fork

---

Tests/Runtime/MonkeyTest.cs

- Use `FileInfo` instead of `File.ReadAllByte` in assertions
- Add `Description` attribute to tests that require visual confirmation

Refactor tests

---

.editorconfig

see: https://youtrack.jetbrains.com/issue/RIDER-102981/File-Header-Template-variables-no-longer-being-replaced

Fix header template variables

---

.github/workflows/test.yml
Makefile
README.md
Runtime/ScreenshotOptions.cs
Tests/Runtime/MonkeyTest.cs
package.json

Changed the default screenshot save directory.
This feature is inherited from test-helper v0.5. see: https://github.com/nowsprinting/test-helper/pull/63
Application.persistentDataPath+/TestHelper.Monkey/Screenshots
First, command line argument "-testHelperScreenshotDirectory".
If the command line argument is omitted, <c>Application.persistentDataPath</c> + "/TestHelper/Screenshots/" is used. (removed `.Monkey`)

Add command line argument to specify screenshot save directory

---

Runtime/ScreenshotOptions.cs

Default directory is set by the test-helper package.
null is ok here.

Refactor set default screenshot save directory to null

---

Runtime/GameObjectFinder.cs
Runtime/Hints/InteractiveComponentHint.cs
Runtime/InteractiveComponent.cs
Runtime/InteractiveComponentCollector.cs
Runtime/Monkey.cs
Tests/Runtime/Annotations/PositionAnnotationTest.cs
Tests/Runtime/InteractiveComponentCollectorTest.cs
Tests/Runtime/InteractiveComponentTest.cs
Tests/Runtime/MonkeyTest.cs
Tests/Runtime/Operators/ClickOperatorTest.cs
Tests/Runtime/Operators/TextInputOperatorTest.cs
Tests/Runtime/Operators/TouchAndHoldOperatorTest.cs

Refactor relative to #102
- Add and use ScreenPointStrategy and ReachableStrategy into instance field of InteractiveComponent
- Add and use ScreenPointStrategy, ComponentInteractableStrategy, and ReachableStrategy into instance field of InteractiveComponentCollector
- Remove ScreenPointStrategy from parameter of InteractiveComponent operator methods

Refactor InteractiveComponent

---

Annotations/TestHelper.Monkey.Annotations.asmdef
README.md

Since links with annotation components remain in the scenes and prefabs, a warning log will be generated at the time of instantiate.
To avoid this, annotation assembly are included in release builds.

Remove defineConstraints from annotation assembly

---

Runtime/GameObjectFinder.cs
Tests/Runtime/GameObjectFinderTest.cs

- Fix case of GamObjects has the same name in FindByPathAsync
- Add assert minimum timeout seconds

Fix case of GamObjects has the same name in FindByPathAsync

---

README.md
Runtime/Extensions/ComponentExtensions.cs
Runtime/Extensions/GameObjectExtensions.cs
Runtime/Hints/InteractiveComponentHint.cs
Runtime/InteractiveComponent.cs
Runtime/InteractiveComponentCollector.cs
Runtime/Monkey.cs
Samples~/uGUI Demo/Tests/Runtime/ScenarioTest.cs
Tests/Runtime/Annotations/PositionAnnotationTest.cs
Tests/Runtime/Extensions/ComponentExtensionsTest.cs
Tests/Runtime/Extensions/ComponentExtensionsTest.cs.meta
Tests/Runtime/Extensions/GameObjectExtensionsTest.cs
Tests/Runtime/Extensions/GameObjectExtensionsTest.cs.meta
Tests/Runtime/InteractiveComponentTest.cs
Tests/Runtime/MonkeyTest.cs

- Obsolete `InteractiveComponent` class
- Add `ComponentExtensions.SelectOperators` and `SelectOperatorsOfType`
- Add `GameObjectExtensions.GetInteractableComponents`
- Add `GameObjectExtensions.IsReachable`
- Change `Monkey.RunStep` parameters, Passing only necessary fields instead of `MonkeyConfig`

Obsolete InteractiveComponent class

---

Runtime/ScreenshotFilenameStrategies/AbstractPrefixAndUniqueIDStrategy.cs

Condition: when there is a string parameter in a parameterized test

Fix suppress double quote in screenshot filename

---

README.md
Runtime/DefaultStrategies/DefaultComponentInteractableStrategy.cs
Runtime/DefaultStrategies/DefaultReachableStrategy.cs
Runtime/Extensions/GameObjectExtensions.cs
Runtime/GameObjectFinder.cs
Runtime/Hints/InteractiveComponentHint.cs
Runtime/InteractiveComponent.cs
Runtime/InteractiveComponentCollector.cs
Runtime/Monkey.cs
Runtime/MonkeyConfig.cs
Tests/Performance/MonkeyTest.cs
Tests/Performance/TestHelper.Monkey.Performance.Tests.asmdef
Tests/Runtime/Annotations/PositionAnnotationTest.cs
Tests/Runtime/DefaultStrategies.meta
Tests/Runtime/DefaultStrategies/DefaultReachableStrategyTest.cs
Tests/Runtime/DefaultStrategies/DefaultReachableStrategyTest.cs.meta
Tests/Runtime/Extensions/GameObjectExtensionsTest.cs
Tests/Runtime/MonkeyTest.cs
package.json

- Suppress logging screenshot filename (see: https://github.com/nowsprinting/test-helper/pull/80 )
- Unified operates logging includes screenshot filename
- Add take a screenshot when over `SecondsToErrorForNoInteractiveComponent`
- Add `MonkeyConfig.Verbose` option, output lottery entries and failing raycast results if true

Optimize logging and add verbose option

---

.github/dependabot.yml
.github/workflows/actionlint.yml
.github/workflows/create-release-pr.yml
.github/workflows/metacheck.yml
.github/workflows/pr-labeler.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
.github/workflows/test.yml
Makefile

- Add `@stable` virtual dist-tag when installing test-framework package
- Mod openupm command option
- Mod dependency check interval to weekly
- Add timeout-minutes
- Add github.ref into cache key
- Mod log file names to same to game-ci/unity-test-runner
- Fix to code coverage exclude test project assemblies

Fix workflows and Makefile

---

Runtime/DefaultStrategies/DefaultIgnoreStrategy.cs
Runtime/DefaultStrategies/DefaultIgnoreStrategy.cs.meta
Runtime/Monkey.cs
Runtime/MonkeyConfig.cs
Tests/Performance/MonkeyTest.cs
Tests/Runtime/MonkeyTest.cs

Ignored GameObject check rule is implemented inside Monkey.
It can only check if a GameObject has an `IgnoreAnnotation` component.
Ignored GameObject check rule is pluggable.
Users can implement any IsIgnored function.

Ignored GameObject strategy to pluggable

---

Runtime/GameObjectFinder.cs
Runtime/Monkey.cs
Runtime/Operators/UGUIClickAndHoldOperator.cs

Fix the issue where `UniTask.Delay` does not work.
It remains `UniTaskStatus.Pending` when `Time.timescale=0f`.

Fix to work even when Time.timescale=0f

---

Runtime/GameObjectFinder.cs

Set max polling interval to 1 second.

Fix polling interval

---

Runtime/DefaultStrategies/DefaultComponentInteractableStrategy.cs
Runtime/DefaultStrategies/DefaultIgnoreStrategy.cs
Runtime/DefaultStrategies/DefaultScreenPointStrategy.cs
Runtime/Extensions/GameObjectExtensions.cs
Runtime/Operators/UGUITextInputOperator.cs
Tests/Runtime/Annotations/InputFieldAnnotationTest.cs
Tests/Runtime/Annotations/PositionAnnotationTest.cs
Tests/Runtime/DefaultStrategies/DefaultComponentInteractableStrategyTest.cs
Tests/Runtime/DefaultStrategies/DefaultComponentInteractableStrategyTest.cs.meta
Tests/Runtime/DefaultStrategies/DefaultIgnoreStrategyTest.cs
Tests/Runtime/DefaultStrategies/DefaultIgnoreStrategyTest.cs.meta

- Fix to ignore disabled interactable components in `DefaultComponentInteractableStrategy`
- Fix to ignore disabled `IgnoreAnnotation`
- Fix to ignore disabled `InputFieldAnnotation`
- Fix to ignore disabled PositionAnnotations

Fix to exclude component if disabled

---

Annotations/ScreenOffsetAnnotation.cs
Annotations/ScreenPositionAnnotation.cs
README.md
Runtime/DefaultStrategies/DefaultScreenPointStrategy.cs
Tests/Runtime/Annotations/PositionAnnotationTest.cs
Tests/Scenes/ScaledCanvas.unity
Tests/Scenes/ScaledCanvas.unity.meta

Not respect `CanvasScaler` when attaching `ScreenOffsetAnnotation` and `ScreenPositionAnnotation`
Respect `CanvasScaler` when attaching `ScreenOffsetAnnotation` and `ScreenPositionAnnotation`
Calculation cannot be performed if the aspect ratio of CanvasScaler and the runtime display differ.

Fix to respect CanvasScaler

---

Editor/ContextMenu/CopyToClipboardMenu.cs
Editor/ContextMenu/CopyToClipboardMenu.cs.meta
README.md

Select any `GameObject` in the Hierarchy window and right-click to open the context menu, then select **Copy to Clipboard > Hierarchy Path**.
Select any `GameObject` in the Hierarchy window and right-click to open the context menu, then select **Copy to Clipboard > Instance ID**.

Add "Copy to Clipboard" context menu on Hierarchy window

---

README.md
Runtime/Extensions/ComponentExtensions.cs
Runtime/Extensions/GameObjectExtensions.cs
Runtime/InteractableComponentsFinder.cs
Runtime/InteractiveComponent.cs
Runtime/Monkey.cs
Runtime/Operators/IOperator.cs
Runtime/Operators/ITextInputOperator.cs
Runtime/Operators/UGUIClickAndHoldOperator.cs
Runtime/Operators/UGUIClickOperator.cs
Runtime/Operators/UGUITextInputOperator.cs
Runtime/Operators/Utils/OperationLogger.cs
Runtime/Operators/Utils/PointerEventSimulator.cs
Runtime/Operators/Utils/PointerEventSimulator.cs.meta
Runtime/Operators/Utils/SimulatedPointerEventData.cs
Runtime/Operators/Utils/SimulatedPointerEventData.cs.meta
Samples~/uGUI Demo/Tests/Runtime/ScenarioTest.cs
Tests/Runtime/InteractiveComponentTest.cs
Tests/Runtime/MonkeyTest.cs
Tests/Runtime/Operators/UGUIClickAndHoldOperatorTest.cs
Tests/Runtime/Operators/UGUIClickOperatorTest.cs
Tests/Runtime/Operators/UGUITextInputOperatorTest.cs
Tests/Runtime/Operators/Utils/OperationLoggerTest.cs
Tests/Runtime/Operators/Utils/SimulatedPointerEventDataTest.cs
Tests/Runtime/Operators/Utils/SimulatedPointerEventDataTest.cs.meta
Tests/Runtime/TestDoubles/StubDestroyingItselfWhenPointerDown.cs

- Fix to reproduce the sequence of events that happen when pointer-clicking
- Change the Operator's operate target from `Component` to `GameObject`

Change the Operator's operate target from Component to GameObject

---

README.md
Runtime/DefaultStrategies/DefaultReachableStrategy.cs
Runtime/Monkey.cs
Tests/Runtime/DefaultStrategies/DefaultReachableStrategyTest.cs

Before:
```
{1, 2, 3}
```
After:
```
[1, 2, 3]
```

Fix verbose log formatting to use square brackets for lists

---

Tests/Performance/TestHelper.Monkey.Performance.Tests.asmdef

Adopt Unity's naming.
Before: `ENABLED_PERFORMANCE_TESTING`
After `ENABLE_PERFORMANCE_TESTING`
See: https://docs.unity3d.com/Manual/scripting-symbol-reference.html

Fix the define scripting symbol name in tests

---

README.md
Runtime/Extensions/TransformExtensions.cs
Runtime/GameObjectFinder.cs
Runtime/GameObjectMatchers/ButtonMatcher.cs
Runtime/GameObjectMatchers/PathMatcher.cs
Runtime/GameObjectMatchers/ToggleMatcher.cs
Tests/Runtime/Extensions/TransformExtensionsTest.cs

- Fix MatchPath if name includes parentheses case
- Fix to clarify that only wildcards are supported among glob patterns

Fix MatchPath if name includes parentheses case

---

README.md
Runtime/MonkeyConfig.cs

Remove the following operators from the `MonkeyConfig` defaults:
- UguiClickAndHoldOperator
- UguiDoubleClickOperator
- UguiScrollWheelOperator

Reduce default operators

---

Runtime/Monkey.cs
Runtime/MonkeyConfig.cs
Runtime/Operators/UguiDragAndDropOperator.cs
Runtime/Operators/UguiScrollWheelOperator.cs
Runtime/Operators/UguiTextInputOperator.cs
Runtime/Operators/UguiToggleOperator.cs
Runtime/Random/IRandomString.cs
Runtime/Random/IRandomizable.cs
Runtime/Random/IRandomizable.cs.meta
Runtime/Random/RandomStringImpl.cs
Tests/Runtime/TestDoubles/StubRandomString.cs
package.json

The behavior of the operators used in monkey tests cannot be made deterministic.
- `UguiDragAndDropOperator`
- `UguiScrollWheelOperator`
- `UguiTextInputOperator`
This is because the PRNG configured in `MonkeyConfig` is not used.
- Upgrade test-helper.random package from v1.0.0 to v1.1.0
- Add `IRandomizable` interface to allow PRNG injection into operators
- Modify follows operators to implement `IRandomizable` and use injected PRNG instances
- Update monkey test startup to configure PRNG for randomizable operators

Set PRNG instance to randomizable operators when starting up monkey tests

---

.github/workflows/test.yml

- 6000.0.58f1
- 6000.2.4f1
- 6000.1

Upgrade Unity versions used to run tests on CI, and remove 6.1

---

.github/workflows/test.yml
Makefile
Tests/Scenes/Canvas.unity
Tests/Scenes/GameObjectFinderText.unity

The following test scene uses `InputSystemUIInputModule` with the `EventSystem`, so scene validation failed:
- Canvas.unity
- GameObjectFinderText.unity
- Replace to `StandaloneInputModule` insted `InputSystemUIInputModule`
- Remove install com.unity.inputsystem package on run tests

Fix to no need InputSystem
