Runtime/InteractiveComponent.cs
Runtime/Monkey.cs
Runtime/Operators/LongTapOperator.cs
Tests/Runtime/InteractiveComponentCollectorTest.cs
Tests/Runtime/InteractiveComponentTest.cs
Tests/Runtime/MonkeyTest.cs
Tests/Runtime/Operators/ClickOperatorTest.cs
Tests/Runtime/Operators/LongTapOperatorTest.cs
Tests/Runtime/TestDoubles/SpyButtonClickReceiver.cs

- Fix cancel during long tap
- Fix test for task cancel
- Refactor

Fix cancel during long tap

---

Runtime/Monkey.cs
Tests/Runtime/MonkeyTest.cs

- Refactor tests
- Fix bug when Lifetime==TimeSpan.MaxValue

Fix Lifetime overflow error

---

.editorconfig
Runtime/InteractiveComponent.cs
Runtime/InteractiveComponentCollector.cs
Runtime/Monkey.cs
Runtime/MonkeyConfig.cs
Runtime/Random/IRandom.cs
Runtime/Random/RandomImpl.cs
Tests/Runtime/InteractiveComponentCollectorTest.cs

- Update .editorconfig
- Suppress C#8.0 syntax sugar
- Fix warning

Organize EditorConfig

---

.github/workflows/test.yml
.octocov.yml
Makefile

- Fix Makefile
- Add comment into .octocov
- Fix test workflow
- Upgrade create-unity-project-action to v2

Fix test workflow

---

.github/workflows/actionlint.yml
.github/workflows/activation.yml
.github/workflows/create-release-pr.yml
.github/workflows/metacheck.yml
.github/workflows/pr-labeler.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
.github/workflows/test.yml
Makefile

- Remove targetPlatform from matrix
- Support getting assembly name when without Runtime
- Add copyright into workflows

Mod test workflow and Makefile

---

README.md
Runtime/MonkeyConfig.cs

- Fix default lifetime to 1min
- Mod README.md

Mod default lifetime to 1min

---

README.md

- Remove using CancellationToken from sample test code
- Add note about can use runtime code

Remove using CancellationToken from sample test code in README

---

.editorconfig
Makefile

- Fix .editorconfig
- Fix argument in Makefile

Fix Makefile and .editorconfig

---

.github/workflows/test.yml
Makefile
README.md
Tests/Runtime/AssemblyInfo.cs
Tests/Runtime/AssemblyInfo.cs.meta
Tests/Runtime/InteractiveComponentCollectorTest.cs
Tests/Runtime/InteractiveComponentTest.cs
Tests/Runtime/MonkeyTest.cs
Tests/Runtime/TestHelper.Monkey.Tests.asmdef

- Fix tests using GameViewResolutionAttribute
- Add install test-helper package into Makefile and test workflow
- Fix README.md

Fix tests using GameViewResolutionAttribute

---

README.md
Tests/Runtime/InteractiveComponentCollectorTest.cs
Tests/Runtime/InteractiveComponentTest.cs
Tests/Runtime/MonkeyTest.cs
Tests/Runtime/Operators/ClickOperatorTest.cs
Tests/Runtime/Operators/TouchAndHoldOperatorTest.cs
Tests/Runtime/TestDoubles/StubDestroyingItselfWhenPointerDown.cs

- Bump test required package versions in README.md
- Refactor tests using LoadSceneAttribute (Required test-helper package v0.3.0 or later)

Refactor tests

---

README.md
Runtime/Monkey.cs
Runtime/MonkeyConfig.cs
Runtime/TestHelper.Monkey.asmdef
Tests/Runtime/MonkeyTest.cs
Tests/Runtime/TestHelper.Monkey.Tests.asmdef
package.json

- Add dependency com.nowsprinting.test-helper v0.4.0
- Add show Gizmos option
refs #45

Add show Gizmos option

---

.github/workflows/test.yml
README.md
Runtime/Monkey.cs
Runtime/MonkeyConfig.cs
Tests/Runtime/MonkeyTest.cs
package.json

Configurations in `MonkeyConfig`:
- **TakeScreenshots**: Take screenshots each step if true
- **ScreenshotsDirectory**: Directory path to save screenshots. Default save path is `Application.persistentDataPath` + "/TestHelper.Monkey/Screenshots/".
- **ScreenshotsFilenamePrefix**: Prefix of screenshots filename. Default prefix is `CurrentTest.Name` when run in test-framework context. Using caller method name when run in runtime context.

Add take screenshots option

---

.github/release-drafter.yml

Mod emoji in releases

---

Runtime/Monkey.cs
Runtime/MonkeyConfig.cs
Runtime/Random/IRandom.cs
Runtime/Random/RandomImpl.cs
Runtime/TestHelper.Monkey.asmdef
Tests/Runtime/MonkeyTest.cs
Tests/Runtime/TestDoubles/StubRandom.cs
Tests/Runtime/TestHelper.Monkey.Tests.asmdef
package.json

- Update dependencies
- Replace random implement from TestHelper.Monkey.Random to TestHelper.Random
- Obsolete TestHelper.Monkey.Random

Replace the random implementation with TestHelper.Random package

---

README.md
Runtime/Monkey.cs
Runtime/MonkeyConfig.cs
Runtime/ScreenshotOptions.cs
Runtime/ScreenshotOptions.cs.meta
Tests/Runtime/MonkeyTest.cs

- Mod fields to properties in MonkeyConfig.cs
- Mod screenshot options
- Fix duplicate created GameObjects for take screenshots

Fix screenshot options

---

Tests/Runtime/TestDoubles/StubRandom.cs
package.json

- Update test-helper.random package to v0.2.0
- Fix test stubs

Update test-helper.random package to v0.2.0

---

.github/workflows/test.yml

- Add email and password to unity-test-runner
- Upgrade Unity versions running on workflows

Add email and password to unity-test-runner

---

.github/workflows/test.yml
Makefile

refs https://github.com/openupm/openupm-cli/issues/156

[TEMPORARY] Add specify version number for com.unity packages

---

Runtime/ScreenshotOptions.cs
Tests/Runtime/MonkeyTest.cs
Tests/Runtime/ScreenshotFilenameStrategies/CounterBasedStrategyTest.cs

Fix minor recommend

---

.github/workflows/test.yml
Makefile

Reverts PR #83 
This problem is fixed in openupm-cli v1.19.11.

Revert "[TEMPORARY] Add specify version number for com.unity packages"

---

.github/release-pr-template.md
Samples~/TestHelper.Monkey.Demo.meta
Samples~/TestHelper.Monkey.Demo/Scenes.meta
Samples~/TestHelper.Monkey.Demo/Scenes/Demo.unity
Samples~/TestHelper.Monkey.Demo/Scenes/Demo.unity.meta
Samples~/TestHelper.Monkey.Demo/Scripts.meta
Samples~/TestHelper.Monkey.Demo/Scripts/Runtime.meta
Samples~/TestHelper.Monkey.Demo/Scripts/Runtime/MonkeyController.cs
Samples~/TestHelper.Monkey.Demo/Scripts/Runtime/MonkeyController.cs.meta
Samples~/TestHelper.Monkey.Demo/Scripts/Runtime/TestHelper.Monkey.Demo.asmdef
Samples~/TestHelper.Monkey.Demo/Scripts/Runtime/TestHelper.Monkey.Demo.asmdef.meta
Samples~/TestHelper.Monkey.Demo/Tests.meta
Samples~/TestHelper.Monkey.Demo/Tests/Runtime.meta
Samples~/TestHelper.Monkey.Demo/Tests/Runtime/MonkeyTest.cs
Samples~/TestHelper.Monkey.Demo/Tests/Runtime/MonkeyTest.cs.meta
Samples~/TestHelper.Monkey.Demo/Tests/Runtime/TestHelper.Monkey.Demo.Tests.asmdef
Samples~/TestHelper.Monkey.Demo/Tests/Runtime/TestHelper.Monkey.Demo.Tests.asmdef.meta
package.json

Add demo app and tests.
The demo app can run monkey testing from outside the tests.

Add demo app into Samples

---

Tests/Runtime/Annotations/InputFieldAnnotationTest.cs
Tests/Runtime/Annotations/PositionAnnotationTest.cs
Tests/Runtime/AssemblyInfo.cs
Tests/Runtime/AssemblyInfo.cs.meta
Tests/Runtime/Hints/InteractiveComponentHintPositionTest.cs
Tests/Runtime/InteractiveComponentCollectorTest.cs
Tests/Runtime/InteractiveComponentTest.cs
Tests/Runtime/MonkeyTest.cs
Tests/Runtime/Operators/ClickOperatorTest.cs
Tests/Runtime/Operators/TextInputOperatorTest.cs
Tests/Runtime/Operators/TouchAndHoldOperatorTest.cs
Tests/Scenes/MonkeyUiScreenSpaceCamera.unity
Tests/Scenes/MonkeyUiScreenSpaceOverlay.unity
Tests/Scenes/MonkeyUiWorldSpace.unity

- Fix all tests GameView resolution to VGA
- Fix reduce the execution time of lottery tests

Optimize tests

---

README.md
Runtime/Extensions/TransformExtensions.cs
Runtime/GameObjectFinder.cs
Tests/Runtime/Extensions/TransformExtensionsTest.cs

Fix misspelling

---

Runtime/InteractiveComponent.cs
Runtime/InteractiveComponentCollector.cs
Samples~/uGUI Demo/Tests/Runtime/ScenarioTest.cs
Tests/Runtime/InteractiveComponentTest.cs
Tests/Runtime/MonkeyTest.cs

- Add `CreateInteractableComponent(MonoBehaviour)` and make constructor to internal
- Obsolate `CreateInteractableComponent(GameObject)`

Add CreateInteractableComponent(MonoBehaviour) static method

---

Runtime/InteractiveComponent.cs
Tests/Runtime/InteractiveComponentTest.cs

Before: Returns null
After: Throws ArgumentException

Mod CreateInteractableComponent throws ArgumentException if component is not interactable

---

Annotations/TestHelper.Monkey.Annotations.asmdef
README.md
Runtime/TestHelper.Monkey.asmdef

- Add defineConstraints into runtime asmdef
- Add "Use in runtime code" into README.md

Add defineConstraints for excluded from release builds

---

.github/release-pr-template.md
.github/workflows/test.yml
Samples~/uGUI Demo/Tests/Runtime/MonkeyTest.cs
Samples~/uGUI Demo/Tests/Runtime/ScenarioTest.cs
package.json

- Upgrade depends test-helper package to v0.6.0 (support relative path in `LoadSceneAttribute`)
- Mod scene path to relative in Samples~
- Remove task about changing scene path from release-pr-template.md

Mod scene path to relative in Samples~

---

Runtime/AssemblyInfo.cs
Runtime/InteractiveComponentCollector.cs
Runtime/Monkey.cs
Tests/Performance.meta
Tests/Performance/MonkeyTest.cs
Tests/Performance/MonkeyTest.cs.meta
Tests/Performance/TestHelper.Monkey.Performance.Tests.asmdef
Tests/Performance/TestHelper.Monkey.Performance.Tests.asmdef.meta

- Add performance testing assembly
- Refactor: Add constructor overload
- Add performance tests

Add performance tests

---

Samples~/uGUI Demo/Tests/Runtime/MonkeyTest.cs
Samples~/uGUI Demo/Tests/Runtime/ScenarioTest.cs

- Fix flaky test in the Samples
- Fix warning

Fix flaky test in the Samples

---

.github/workflows/docfx.yml
LICENSE.md
README.md
package.json

- Add docfx workflow
- Mod documentationUrl
- Fix README.md

Add docfx workflow

---

.github/workflows/docfx.yml

Fix docfx workflow

---

Runtime/DefaultStrategies/DefaultReachableStrategy.cs
Tests/Runtime/DefaultStrategies/DefaultReachableStrategyTest.cs

Mod LogError when EventSystem is not found

---

Runtime/InteractableComponentsFinder.cs
Runtime/Monkey.cs
Runtime/Operators/UGUIClickAndHoldOperator.cs
Runtime/Operators/UGUIClickOperator.cs
Runtime/Operators/UGUITextInputOperator.cs
Tests/Runtime/MonkeyTest.cs

- Fix throw exception when operators is null
- Fix verbose lottery entries
- Fix operate log message

Fix throw exception when operators is null

---

.github/workflows/docfx.yml

Mod docfx trigger to on.push.tags and on.release

---

.github/workflows/docfx.yml

Mod docfx trigger to on.workflow_run

---

Runtime/DefaultStrategies/DefaultIgnoreStrategy.cs
Runtime/DefaultStrategies/DefaultReachableStrategy.cs
Tests/Runtime/DefaultStrategies/DefaultReachableStrategyTest.cs
Tests/Runtime/MonkeyTest.cs

- Fix verbose log messages
- Add camera used by raycaster into verbose log messages

Fix verbose log messages

---

README.md
Runtime/Operators/UGUITextInputOperator.cs
Runtime/TestHelper.Monkey.asmdef
Tests/Runtime/Operators/UGUITextInputOperatorTest.cs
Tests/Runtime/TestHelper.Monkey.Tests.asmdef

- Add version defines for TextMesh Pro
- Add support `TMP_InputField`
- with Unity UI package v2.0.0
- with TextMesh Pro package v3.0.6
- without TextMesh Pro

Support TMPro.TMP_InputField

---

README.md
Runtime/Extensions/GameObjectExtensions.cs
Runtime/MonkeyConfig.cs

- Add warning about "Active Input Handling" setting for running tests
- Add about customization and troubleshooting
- Fix wording

Add about customization and troubleshooting into README.md

---

Runtime/DefaultStrategies/DefaultReachableStrategy.cs
Runtime/GameObjectFinder.cs

- Fix not to cache PointerEventData includes EventSystem instance in GameObjectFinder
- Same as #169
- Fix comments in DefaultReachableStrategy

Fix not to cache PointerEventData includes EventSystem instance in GameObjectFinder

---

README.md
Runtime/DefaultStrategies/DefaultIgnoreStrategy.cs
Runtime/DefaultStrategies/DefaultReachableStrategy.cs
Runtime/GameObjectFinder.cs
Tests/Runtime/DefaultStrategies/DefaultReachableStrategyTest.cs
Tests/Runtime/GameObjectFinderTest.cs

- Add verbose logger into GameObjectFinder
- Fix tests
- Fix comments

Add verbose logger into GameObjectFinder

---

Runtime/Operators/UGUIClickAndHoldOperator.cs
Runtime/Operators/UGUIClickOperator.cs
Runtime/Operators/UGUITextInputOperator.cs

- Fix to more reality PointerEventData in ClickOperators
- Fix to select GameObject before setting text in TextInputOperator

Fix to more reality PointerEventData in ClickOperators

---

README.md
Runtime/Exceptions.meta
Runtime/Exceptions/InfiniteLoopException.cs
Runtime/Exceptions/InfiniteLoopException.cs.meta
Runtime/Monkey.cs
Runtime/MonkeyConfig.cs
Tests/Runtime/Annotations/InputFieldAnnotationTest.cs
Tests/Runtime/MonkeyTest.cs
Tests/Runtime/TestComponents/RelayButton.cs
Tests/Runtime/TestComponents/RelayButton.cs.meta
Tests/Scenes/InfiniteLoop.unity
Tests/Scenes/InfiniteLoop.unity.meta

Add `BufferLengthForDetectLooping`: An `InfiniteLoopException` is thrown if a repeating operation is detected within the specified buffer length; default is 10.
Throw `InfiniteLoopException` if a looping operation is detected.

Add infinite loop detection

---

Tests/Runtime/TestComponents/RelayButton.cs

I forgot to uncomment it.
Fixed a bug in #186

Fix to hide from "Add Component" picker

---

Tests/Runtime/MonkeyTest.cs
package.json

- Upgrade dependency test-helper.random package to v0.3.1
- Fix test to fit test-helper.random v0.3.1

Upgrade dependency test-helper.random package to v0.3.1

---

Tests/Runtime/MonkeyTest.cs

Disable loop detection when a large number of trials test.

Fix flaky tests

---

README.md
Runtime/GameObjectFinder.cs
Runtime/InteractableComponentsFinder.cs
Runtime/Monkey.cs

- Add class diagram for default strategies used in `MonkeyConfig`
- Add about `InfiniteLoopException` into troubleshooting
- Fix wording and usage
- Fix parameter name
- Obsolete constructor overload

Fix README.md

---

README.md
Runtime/Exceptions/InfiniteLoopException.cs
Runtime/Monkey.cs
Tests/Runtime/MonkeyTest.cs

- Refactor
- Remove unnecessary `ref` keyword
- Add a message and take a screenshot when `InfiniteLoopException`

Add a message and take a screenshot when InfiniteLoopException

---

Runtime/Operators/UGUIClickAndHoldOperator.cs
Runtime/Operators/UGUIClickOperator.cs
Tests/Runtime/Operators/UGUIClickAndHoldOperatorTest.cs
Tests/Runtime/Operators/UGUIClickOperatorTest.cs
Tests/Runtime/Operators/UGUITextInputOperatorTest.cs
Tests/Scenes/MissingComponent.unity
Tests/Scenes/MissingComponent.unity.meta

- Add missing component tests
- Fix to NullReferenceException if with missing component

Fix NullReferenceException if with missing component

---

.github/release-drafter.yml

Breaking changes to be minor version updates, not major ones.

---

.editorconfig

Fix .editorconfig for test code

---

Runtime/Operators/UguiScrollWheelOperator.cs
Tests/Runtime/Operators/UguiScrollWheelOperatorTest.cs

- Add default value to scrollSpeed in UguiScrollWheelOperator.ctor
- Add cancel test case

Add default value to scrollSpeed in UguiScrollWheelOperator.ctor

---

Runtime/Operators/IToggleOperator.cs
Runtime/Operators/IToggleOperator.cs.meta
Runtime/Operators/UGUIClickAndHoldOperator.cs
Runtime/Operators/UGUIClickOperator.cs
Runtime/Operators/UGUITextInputOperator.cs
Runtime/Operators/UguiDoubleClickOperator.cs
Runtime/Operators/UguiToggleOperator.cs
Runtime/Operators/UguiToggleOperator.cs.meta
Tests/Runtime/Operators/UguiToggleOperatorTest.cs
Tests/Runtime/Operators/UguiToggleOperatorTest.cs.meta

You can click to turn it on/off, or you can specify the on/off state.
Toggle operator for `UnityEngine.UI.Toggle` component.
Fix XML docs

Add UguiToggleOperator

---

Runtime/GameObjectFinder.cs

- Fix unnecessary GameObject searches
- Refactor FindByMatcher

Fix unnecessary GameObject searches

---

.github/release-drafter.yml

This reverts commit a7e5d1e0e9eaf7daf72e6be9387408db59bc1732.
refs #207

Revert "Update release-drafter.yml to categorize breaking changes under minor version"

---

Runtime/Operators/UguiClickAndHoldOperator.cs
Runtime/Operators/UguiClickOperator.cs
Runtime/Operators/UguiDoubleClickOperator.cs
Runtime/Operators/UguiDragAndDropOperator.cs
Runtime/Operators/Utils/PointerClickEventSimulator.cs
Runtime/Operators/Utils/PointerDragEventSimulator.cs

- Add logging on drop on `UguiDragAndDropOperator`
- Fix to suppress verbose log in the pointer event simulators
refs:
- #232

Add logging on drop

---

Annotations/DropAnnotation.cs
Annotations/IgnoreAnnotation.cs
Annotations/InputFieldAnnotation.cs
Annotations/ScreenOffsetAnnotation.cs
Annotations/ScreenPositionAnnotation.cs
Annotations/WorldOffsetAnnotation.cs
Annotations/WorldPositionAnnotation.cs

- `AddComponentMenuAttribute`
- `HelpURLAttribute`

Add AddComponentMenu and HelpURL attributes to annotation components

---

Samples~/uGUI Demo/Scenes/uGUIDemo.unity
Samples~/uGUI Demo/Scripts/Runtime/EventHandlers/AbstractSpyEventHandler.cs
Samples~/uGUI Demo/Scripts/Runtime/EventHandlers/EventPopup.cs
Samples~/uGUI Demo/Scripts/Runtime/MonkeyTestsButton.cs
Samples~/uGUI Demo/Scripts/Runtime/PaginatorButton.cs
Samples~/uGUI Demo/Tests/Runtime/MonkeyTest.cs

- Mod event popup spacing to narrow
- Mod `BufferLengthForDetectLooping` to longer
- Fix popup parent
- Mod handling events

Fix uGUI demo
